<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Biller\Connect\Block\Adminhtml\System\Config\Button\Credentials;

/**
 * @see \Biller\Connect\Block\Adminhtml\System\Config\Button\Credentials
 * @var Credentials $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_api');
        jQuery('#biller-button_credentials').click(function () {
            var params = {
                "username": jQuery("input[name='groups[connection][fields][username][value]']").val(),
                "password": jQuery("input[name='groups[connection][fields][password][value]']").val(),
                "sandbox_username": jQuery("input[name='groups[connection][fields][sandbox_username][value]']").val(),
                "sandbox_password": jQuery("input[name='groups[connection][fields][sandbox_password][value]']").val(),
                "mode": jQuery("select[name='groups[connection][fields][mode][value]']").val(),
            };
            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        if (typeof json.msg != 'undefined') {
                            resultText = json.msg;
                            jQuery("input[name='groups[connection][fields][account][value]']").val(json.account)
                        }
                    }
                    resultSpan.find('.result').show();
                    resultSpan.find('.result').html(resultText);
                }
            });
        });
    });
</script>
<?= $block->getButtonHtml() ?>
<div id="result_api">
    <span class="connecting" style="display: none;">Connecting...</span>
    <span class="result"></span>
</div>
