<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Biller\Connect\Block\Adminhtml\System\Config\Button\DebugCheck;

/**
 * @see \Biller\Connect\Block\Adminhtml\System\Config\Button\DebugCheck
 * @var DebugCheck $block
 */
?>
<div id="mm-biller-result_debug-modal"
     data-mm-biller-endpoind-url="<?= $block->escapeUrl($block->getDebugCheckUrl()) ?>">
    <div id="mm-biller-result_debug">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>

