<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Biller\Connect\Block\Adminhtml\System\Config\Button\ErrorCheck;

/**
 * @see \Biller\Connect\Block\Adminhtml\System\Config\Button\ErrorCheck
 * @var ErrorCheck $block
 */
?>
<div id="mm-biller-result_error-modal"
     data-mm-biller-endpoind-url="<?= $block->escapeUrl($block->getErrorCheckUrl()) ?>">
    <div id="mm-biller-result_error">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
