<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Biller\Connect\Block\Adminhtml\System\Config\Button\Selftest;

/**
 * @see \Biller\Connect\Block\Adminhtml\System\Config\Button\Selftest
 * @var Selftest $block
 */
?>
<div id="mm-biller-result_test-modal" data-mm-biller-endpoind-url="<?= $block->escapeUrl($block->getSelftestUrl()) ?>">
    <div id="mm-biller-result_test">
        <ul class="result"></ul>
    </div>
</div>
